[package]
authors = ["Andy Bell <andyjsbell@gmail.com>"]
name = "simple-pow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.1"
hex = "0.4.3"
hex-literal = "0.3.4"